fail_fast: false
repos:
  - repo: https://github.com/HaoXianSen/Objective-CLint.git
    rev: v0.0.4
    hooks:
      - id: objc-lint
        name: objc-format
        entry: format-objc-hook
        language: script
        require_serial: true
        verbose: true

  - repo: https://github.com/realm/SwiftLint
    rev: 0.49.1
    hooks:
    - id: swiftlint
